// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Bysykkel info
//
//	Test API for accessing Oslo Bysykkel info
//	Schemes:
//	  http
//	Host: localhost:8085
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
