// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Test API for accessing Oslo Bysykkel info",
    "title": "Bysykkel info",
    "version": "1.0.0"
  },
  "host": "localhost:8085",
  "paths": {
    "/stations": {
      "get": {
        "summary": "Get stations info",
        "operationId": "getStationsInfo",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/StationStatusResponse"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "StationInfo": {
      "type": "object",
      "properties": {
        "bikesAvailable": {
          "type": "integer"
        },
        "docksAvailable": {
          "type": "integer"
        },
        "last_reported": {
          "type": "integer"
        },
        "stationName": {
          "type": "string"
        },
        "station_id": {
          "type": "string"
        }
      }
    },
    "StationStatusResponse": {
      "type": "object",
      "properties": {
        "stations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StationInfo"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "description": "Test API for accessing Oslo Bysykkel info",
    "title": "Bysykkel info",
    "version": "1.0.0"
  },
  "host": "localhost:8085",
  "paths": {
    "/stations": {
      "get": {
        "summary": "Get stations info",
        "operationId": "getStationsInfo",
        "responses": {
          "200": {
            "description": "Successful response",
            "schema": {
              "$ref": "#/definitions/StationStatusResponse"
            }
          },
          "500": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "properties": {
        "code": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "StationInfo": {
      "type": "object",
      "properties": {
        "bikesAvailable": {
          "type": "integer"
        },
        "docksAvailable": {
          "type": "integer"
        },
        "last_reported": {
          "type": "integer"
        },
        "stationName": {
          "type": "string"
        },
        "station_id": {
          "type": "string"
        }
      }
    },
    "StationStatusResponse": {
      "type": "object",
      "properties": {
        "stations": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/StationInfo"
          }
        }
      }
    }
  }
}`))
}
