swagger: "2.0"
info:
  title: Bysykkel info
  version: 1.0.0
  description: Test API for accessing Oslo Bysykkel info
host: localhost:8085
paths:
  /stations:
    get:
      summary: Get stations info
      operationId: getStationsInfo
      responses:
        200:
          description: Successful response
          schema:
            $ref: '#/definitions/StationStatusResponse'
        500:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  StationStatusResponse:
    type: object
    properties:
      stations:
        type: array
        items:
            $ref: '#/definitions/StationInfo'
  StationInfo:
    type: object
    properties:
      stationName:
        type: string
      bikesAvailable:
        type: integer
      docksAvailable:
        type: integer
      stationId:
        type: string
      latitude:
        type: number
        format: float
      longitude:
        type: number
        format: float
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
