// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"bysykkel/internal/api/models"
)

// GetStationsInfoOKCode is the HTTP code returned for type GetStationsInfoOK
const GetStationsInfoOKCode int = 200

/*
GetStationsInfoOK Successful response

swagger:response getStationsInfoOK
*/
type GetStationsInfoOK struct {

	/*
	  In: Body
	*/
	Payload *models.StationStatusResponse `json:"body,omitempty"`
}

// NewGetStationsInfoOK creates GetStationsInfoOK with default headers values
func NewGetStationsInfoOK() *GetStationsInfoOK {

	return &GetStationsInfoOK{}
}

// WithPayload adds the payload to the get stations info o k response
func (o *GetStationsInfoOK) WithPayload(payload *models.StationStatusResponse) *GetStationsInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get stations info o k response
func (o *GetStationsInfoOK) SetPayload(payload *models.StationStatusResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStationsInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetStationsInfoInternalServerErrorCode is the HTTP code returned for type GetStationsInfoInternalServerError
const GetStationsInfoInternalServerErrorCode int = 500

/*
GetStationsInfoInternalServerError Unexpected error

swagger:response getStationsInfoInternalServerError
*/
type GetStationsInfoInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetStationsInfoInternalServerError creates GetStationsInfoInternalServerError with default headers values
func NewGetStationsInfoInternalServerError() *GetStationsInfoInternalServerError {

	return &GetStationsInfoInternalServerError{}
}

// WithPayload adds the payload to the get stations info internal server error response
func (o *GetStationsInfoInternalServerError) WithPayload(payload *models.Error) *GetStationsInfoInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get stations info internal server error response
func (o *GetStationsInfoInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStationsInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
