// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStationsInfoHandlerFunc turns a function with the right signature into a get stations info handler
type GetStationsInfoHandlerFunc func(GetStationsInfoParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStationsInfoHandlerFunc) Handle(params GetStationsInfoParams) middleware.Responder {
	return fn(params)
}

// GetStationsInfoHandler interface for that can handle valid get stations info params
type GetStationsInfoHandler interface {
	Handle(GetStationsInfoParams) middleware.Responder
}

// NewGetStationsInfo creates a new http.Handler for the get stations info operation
func NewGetStationsInfo(ctx *middleware.Context, handler GetStationsInfoHandler) *GetStationsInfo {
	return &GetStationsInfo{Context: ctx, Handler: handler}
}

/*
	GetStationsInfo swagger:route GET /stations getStationsInfo

Get stations info
*/
type GetStationsInfo struct {
	Context *middleware.Context
	Handler GetStationsInfoHandler
}

func (o *GetStationsInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetStationsInfoParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
